// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnb0DVXegJUkjtWoSx8XiXyZcIh3nyWg4',
    appId: '1:600243686836:web:b1a1c1720d542a05ee76e1',
    messagingSenderId: '600243686836',
    projectId: 'updateprofileproject',
    authDomain: 'updateprofileproject.firebaseapp.com',
    databaseURL: 'https://updateprofileproject-default-rtdb.firebaseio.com',
    storageBucket: 'updateprofileproject.appspot.com',
    measurementId: 'G-7CGWY51E9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu-33rzTGHuolV9RQ0p2UPeqgNOzRveBw',
    appId: '1:600243686836:android:0ef452a10a1c6b3cee76e1',
    messagingSenderId: '600243686836',
    projectId: 'updateprofileproject',
    databaseURL: 'https://updateprofileproject-default-rtdb.firebaseio.com',
    storageBucket: 'updateprofileproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlzURfuwcnrLR2p5Avzy14ARL8OM5ZpfA',
    appId: '1:600243686836:ios:8304e504a4b332bdee76e1',
    messagingSenderId: '600243686836',
    projectId: 'updateprofileproject',
    databaseURL: 'https://updateprofileproject-default-rtdb.firebaseio.com',
    storageBucket: 'updateprofileproject.appspot.com',
    iosClientId: '600243686836-0o6mosh4ldetfjlq8tdurba5cg90b2e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileUpdateFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlzURfuwcnrLR2p5Avzy14ARL8OM5ZpfA',
    appId: '1:600243686836:ios:b34499275d751f41ee76e1',
    messagingSenderId: '600243686836',
    projectId: 'updateprofileproject',
    databaseURL: 'https://updateprofileproject-default-rtdb.firebaseio.com',
    storageBucket: 'updateprofileproject.appspot.com',
    iosClientId: '600243686836-hpfbmre0uc1pl6i6t39g8fdeq648sjrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileUpdateFirebase.RunnerTests',
  );
}
